"""empty message

Revision ID: 729c1a181ad1
Revises: ab2d91df2b19
Create Date: 2019-12-30 15:27:52.905593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729c1a181ad1'
down_revision = 'ab2d91df2b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('num_upcoming_shows', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'num_upcoming_shows')
    # ### end Alembic commands ###
