"""empty message

Revision ID: 8b5d77f6980b
Revises: e481f4bfd9bb
Create Date: 2019-12-30 17:52:40.651721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5d77f6980b'
down_revision = 'e481f4bfd9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows_count', sa.Integer()))
    op.drop_column('Venue', 'num_upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('num_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Venue', 'upcoming_shows_count')
    # ### end Alembic commands ###
