"""empty message

Revision ID: 987773779498
Revises: 158574cc6f4b
Create Date: 2020-01-03 16:22:44.268130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987773779498'
down_revision = '158574cc6f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'timestamp')
    op.drop_column('Artist', 'timestamp')
    # ### end Alembic commands ###
